name: Lion-Authentication (CI Workflow)

on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - main
  schedule:
    - cron: "15 0 * * *"

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    name: Install PHP Dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, gd, zip, xdebug
          coverage: xdebug
          ini-values: |
            xdebug.mode=coverage
            xdebug.start_with_request=yes
            xdebug.log_level=0
          tools: composer

      - name: Install PHP dependencies
        run: composer install

      - name: Cache vendor directory
        uses: actions/cache@v4
        with:
          path: vendor
          key: php-vendor-${{ runner.os }}-${{ github.run_id }}
          restore-keys: php-vendor-${{ runner.os }}-${{ github.run_id }}

      - name: Cache composer.lock
        uses: actions/cache@v4
        with:
          path: composer.lock
          key: php-composer-lock-${{ runner.os }}-${{ github.run_id }}
          restore-keys: php-composer-lock-${{ runner.os }}-${{ github.run_id }}

  code-analyze:
    runs-on: ubuntu-latest
    name: PHP Code Analyze
    needs:
      - install-dependencies

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, gd, zip

      - name: Restore composer.lock from cache
        uses: actions/cache@v4
        with:
          path: composer.lock
          key: php-composer-lock-${{ runner.os }}-${{ github.run_id }}
          restore-keys: php-composer-lock-${{ runner.os }}-${{ github.run_id }}

      - name: Restore vendor directory from cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: php-vendor-${{ runner.os }}-${{ github.run_id }}
          restore-keys: php-vendor-${{ runner.os }}-${{ github.run_id }}

      - name: PHP CodeSnifer (Src)
        run: php vendor/bin/phpcs --standard=PSR12 src

      - name: PHPStan (Src)
        run: php -d memory_limit=-1 vendor/bin/phpstan analyse --level max src

      - name: PHP CodeSnifer (Tests)
        run: php vendor/bin/phpcs --standard=PSR12 tests

      - name: PHPStan (Tests)
        run: php -d memory_limit=-1 vendor/bin/phpstan analyse --level max tests

  tests:
    runs-on: ubuntu-latest
    name: PHP Tests
    needs: code-analyze

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: mbstring, gd, zip, pdo, pdo_mysql, pdo_pgsql, redis, xdebug
          coverage: xdebug
          ini-values: |
            xdebug.mode=coverage
            xdebug.start_with_request=yes
            xdebug.log_level=0
          tools: composer

      - name: Restore composer.lock from cache
        uses: actions/cache@v4
        with:
          path: composer.lock
          key: php-composer-lock-${{ runner.os }}-${{ github.run_id }}
          restore-keys: php-composer-lock-${{ runner.os }}-${{ github.run_id }}

      - name: Restore vendor directory from cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: php-vendor-${{ runner.os }}-${{ github.run_id }}
          restore-keys: php-vendor-${{ runner.os }}-${{ github.run_id }}

      - name: Run tests
        run: php vendor/bin/phpunit --coverage-clover tests/build/logs/clover.xml --coverage-html tests/build/coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: tests/build/logs/clover.xml
          token: ${{ secrets.CODECOV_TOKEN_LION_AUTHENTICATION }}
